package com.example.umind.ui.theme

import androidx.compose.ui.graphics.Color

// Brand and interactive colors
val Primary = Color(0xFF3B82F6)
val PrimaryPressed = Color(0xFF2563EB)
val PrimarySoft = Color(0xFF60A5FA)
val OnPrimary = Color(0xFFFFFFFF)

// Dark scheme (immersive default)
val DarkBackground = Color(0xFF0B1220)
val DarkOnBackground = Color(0xFFF8FAFC)
val DarkSurface = Color(0xFF111827)
val DarkOnSurface = Color(0xFFF8FAFC)
val DarkSurfaceVariant = Color(0xFF1F2937)
val DarkOnSurfaceVariant = Color(0xFF94A3B8)
val DarkOutline = Color(0xFF334155)
val DarkOutlineVariant = Color(0xFF243244)
val DarkPrimaryContainer = Color(0xFF1E3A63)
val DarkOnPrimaryContainer = Color(0xFFD9E8FF)
val DarkSecondary = Color(0xFF8B9BB8)
val DarkOnSecondary = Color(0xFF0B1220)
val DarkSecondaryContainer = Color(0xFF243244)
val DarkOnSecondaryContainer = Color(0xFFD2DEEF)
val DarkTertiary = Color(0xFF7DD3FC)
val DarkOnTertiary = Color(0xFF082F49)
val DarkTertiaryContainer = Color(0xFF0C4A6E)
val DarkOnTertiaryContainer = Color(0xFFD8F0FF)

// Light scheme (same brand tone)
val LightBackground = Color(0xFFF3F7FF)
val LightOnBackground = Color(0xFF0F172A)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF0F172A)
val LightSurfaceVariant = Color(0xFFF1F5F9)
val LightOnSurfaceVariant = Color(0xFF64748B)
val LightOutline = Color(0xFFCBD5E1)
val LightOutlineVariant = Color(0xFFE2E8F0)
val LightPrimaryContainer = Color(0xFFDCE9FF)
val LightOnPrimaryContainer = Color(0xFF102A43)
val LightSecondary = Color(0xFF475569)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE2E8F0)
val LightOnSecondaryContainer = Color(0xFF1E293B)
val LightTertiary = Color(0xFF0EA5E9)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFE0F2FE)
val LightOnTertiaryContainer = Color(0xFF0C4A6E)

// Feedback
val Success = Color(0xFF22C55E)
val OnSuccess = Color(0xFFFFFFFF)
val Warning = Color(0xFFF59E0B)
val OnWarning = Color(0xFF111827)
val Error = Color(0xFFEF4444)
val OnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFEE2E2)
val LightOnErrorContainer = Color(0xFF7F1D1D)
val DarkErrorContainer = Color(0xFF7F1D1D)
val DarkOnErrorContainer = Color(0xFFFEE2E2)
